### PR TITLE
Fix FILE_DIALOG_GRID in dark theme, removed typo filedlg log

### PR DESCRIPTION
**Pull request by Doado**
Removed typo in logging message in file "filedlg.d"

### CODE REVIEW

**Comment by Doado** [comment]
This fix concerned line 568 in filedlg.d:

debug Log.d("root list styleId=", res.styleId);

2017-11-29 9:17 GMT+00:00 Andrzej Kilijański <notifications@github.com>:

**Comment by and3md** [comment]
You pushed 2 commits to this PR branch, fix from #522 is here too. See file changes tab.

**Comment by Doado** [comment]
Argh, git always gets me somehow. Can you delete it or will I have to do it?

2017-11-29 9:39 GMT+00:00 Andrzej Kilijański <notifications@github.com>:

**Comment by and3md** [comment]
OK, I close #522 and change #523 subject (#523 will merge your 2 commits).

**Comment by Doado** [comment]
Cool. Thanks.

2017-11-29 10:00 GMT+00:00 Andrzej Kilijański <notifications@github.com>:

**Pull request merged**
