### PR TITLE
Rewrote the decodeHexColor function

### PR DESCRIPTION
**Pull request by bagomot**
**Added:** 

- `rgb(r, g, b)` format, like: `rgb(255, 255, 255) `
- `rgba(r, g, b, a)` format, like: `rgba(255, 255, 255, .5) ` or `rgba(255, 255, 255, 50%)`
- support for enum Color to get color by name
- unit tests

All colors with transparency are still encoded in ARGB format.

### CODE REVIEW

**Comment by GrimMaple** [comment]
Can you please rebase on master?

**Comment by GrimMaple** [comment]
Can you please add unit tests for invalid inputs as well?
It looks like this code will accept stuff like `rgb(321, 321, 321)`.

**Comment by bagomot** [comment]
> Can you please rebase on master?

What is meant? The code is already in the master branch.

> Can you please add unit tests for invalid inputs as well?
> It looks like this code will accept stuff like `rgb(321, 321, 321)`.

Ok. I will add.

**Comment by GrimMaple** [comment]
Why did you close the PR?

What I meant was, the PR has 2 commits (1 merge commit and 1 normal commit). I would appreciate it if you squashed & rebased on master instead, so the commit history doesn't have unnecessary commits.

**Comment by bagomot** [comment]
> Why did you close the PR?
> 
> What I meant was, the PR has 2 commits (1 merge commit and 1 normal commit). I would appreciate it if you squashed & rebased on master instead, so the commit history doesn't have unnecessary commits.

I found errors in the function. I'll fix it and make a new PR or reopen this one.

**Pull request closed without merging**
