### PR TITLE
Better support for many wraplines in word wrap

### PR DESCRIPTION
**Pull request by triplejam**
Improvements to word wrap. Previously could not scroll through an individual line. This adds that ability. Some other small additions still need to be made for this such as the page up and down keys and allowing scrolling down further.

### CODE REVIEW

**Comment by and3md** [comment]
Hi I just tried to test trunk and your branch in example1 EditBox. Can you test wordWrap in example1? Just add:

`ed1.wordWrap = true;` in line 543 (this is editbox on first tab) It's small so it's easy to test?

There are some issues when wrapped line starts be bigger than view. Content start blinking.  If first or last line are wrapped you can't go to the next line by arrow up/down keys. Maybe should I change some other options in EditBox before test?

**Comment by triplejam** [comment]
Made a fix for the last line.

**Comment by triplejam** [comment]
Do you have some text which would be a good example to test against?

**Comment by and3md** [comment]
I did not enter any specific text. In example 1:
Test 1:
Set cursor on the end of first line ("Some text in EditBox") and simply write a lot of random letters without pressing the Enter key so that the widget is filled with text. When the "paragraph" is larger than the control area the content begins to behave strangely.

Test 2:
Clear everything and add two "paragraphs" so that everyone takes a few lines and try to move the cursor with the arrow keys from the first line of text to the last one.

**Comment by triplejam** [comment]
I see what you're saying for the first test. There's just still a lot of small additions to be made. The fix I just made should address the second.

**Comment by and3md** [comment]
I just pull your wordwrap4 branch and not working for me, see screenshot: 

obraz

Cursor can't go down by arrow down key. Clicking scrollbar down button can't show last line too.

**Comment by and3md** [comment]
Here is text that i have in this edit box when try to go down:
```
Some text in EditBox
One more line
fdsfdsf

fdsfdsf

fdsfds
fdsf
Yet another text line asdfdsafdsf dsfmdsf sd f dsf dsf dsf dsf dsfds
```
No empty line on beginning and end.

**Comment by and3md** [comment]
You can try change:
```
    override void wordWrapRefresh()
    {
        _extendRightScrollBound=!_wordWrap;
        _needRewrap = true;
    }

```
and max line width setting:
```
    override protected void updateMaxLineWidth() {
        if (_wordWrap) {
            _maxLineWidth = clientRect.width;
            return;
        }
        // find max line width. TODO: optimize!!!
        int maxw;
        int[] buf;
        for (int i = 0; i < _content.length; i++) {
            dstring s = _content[i];
            int w = calcLineWidth(s);
            if (maxw < w)
                maxw = w;
        }
        _maxLineWidth = maxw;
    }
```

Then horizontal scrollbar will be empty and not grow when typing. 

After this only two thing will remain:
- test1
- selection sometimes is not visible,

**Comment by triplejam** [comment]
Ok, going to work on it some more first.

**Comment by and3md** [comment]
Another hint: The selection starts to be invisible when I change content. I found that draw selection is working (but only first line from paragraph) when remove from drawLineBackground():

```
if (!rc.empty && _wordWrap)
            {
                wordWrapFillRect(buf, lineIndex, rc, focused ? _selectionColorFocused : _selectionColorNormal);
}
```

So I think most likely you should start debug in `wordWrapFillRect()` or maybe after content change there is something not updated?

**Pull request closed without merging**
