### PR TITLE
remove trailing whitespace

### PR DESCRIPTION
**Pull request by John-Colvin**
Might as well do it all at once...

### CODE REVIEW

**Comment by John-Colvin** [comment]
see https://github.com/buggins/dlangui/pull/411/files?w=1 to verify there are only whitespace changes here

**Comment by buggins** [comment]
I hope CI build failure for one configuration is just by accident.

**Comment by John-Colvin** [comment]
Why closed?

**Comment by John-Colvin** [comment]
ping?

**Comment by and3md** [comment]
I asked buggins about this in mail (no answer yet) but maybe I found problem. In dlangide when you add new empty line it adds spaces to do indentation. From this you have a lot of empty lines with spaces. So maybe first dlangide need changes.

**Comment by buggins** [comment]
Closed by accident?

**Comment by John-Colvin** [comment]
#417

**Comment by buggins** [comment]
merged

**Pull request closed without merging**
