### PR TITLE
Fix for issue 249

### PR DESCRIPTION
**Pull request by triplejam**
I wanted to try out the dminer example and got the error described in the issue. For reference, I use 64-bit Linux with nouveau drivers. This is what fixed it for me.

Note: I do not know if it will mess up use with any older opengl versions. If so, another compatability check may need to be added to glsupport.d

Edit: Program says I have glslVersion = 4.30

### CODE REVIEW

**Comment by triplejam** [comment]
@buggins what is a good way to test different versions?

**Comment by dayllenger** [comment]
By the way, you can test your changes on old context using properties `Platform.instance.GLVersionMajor` and `Platform.instance.GLVersionMinor`. There are already compatibility fixes [here](https://github.com/buggins/dlangui/blob/master/src/dlangui/graphics/glsupport.d#L158).

**Comment by triplejam** [comment]
If that is true, then my changes appear to be good.

**Comment by dayllenger** [comment]
I don't think so. Compatibility fixes replace `outColor` with `gl_FragColor`, but you wrote `_fragColor`. Also the issue was with `varying` keyword, so need to replace `varying` and `attribute` in fragment and vertex shaders.

**Comment by triplejam** [comment]
That could be it too. I don't know for sure. However, gl_FragColor is technically deprecated from version 3.1 forward. So if I understand correctly, it was originally `outColor`, then became `gl_FragColor` and then as of version 3.1 you're supposed to just define your own variable to use. The error in the issue results from the lack of the global variable. I'm pretty new to how glsl works, this is just what fixed the problem for me.

**Comment by triplejam** [comment]
@dayllenger This is what led me to this conclusion: https://stackoverflow.com/questions/26695253/when-switching-to-glsl-300-met-the-following-error

**Comment by dayllenger** [comment]
`outColor` is just a dlangui convention. Before shader compilation dlangui replaces `outColor` with `gl_FragColor` in case of old GLSL. So you need to write `outColor`, otherwise on old machine shader will be broken.

**Comment by triplejam** [comment]
> outColor is just a dlangui convention.

Okay

**Pull request merged**
