### PR TITLE
A little better dml

### PR DESCRIPTION
**Pull request by xucs007**
Sorted attributes. DockWin made left column width able to adjust.

### CODE REVIEW

**Comment by GrimMaple** [comment]
Please, squash the commits into one. Feel free to force push if needed :)

**Comment by GrimMaple** [comment]
Please, remove the screenshot -- it's not needed

**Comment by xucs007** [comment]
Ok, done.

**Comment by GrimMaple** [comment]
I really enjoy what you did there. I think this improves the quality of dmledit by alot :)

**Comment by xucs007** [comment]
Who are supposed to merge my this pull request?

**Pull request merged**
