### PR TITLE
Fix compilation for DMD 2.090

### PR DESCRIPTION
**Pull request by NotSpooky**
Could someone test this please?

### CODE REVIEW

**Comment by ShigekiKarita** [comment]
Hi, I also met this error. Can you take a look at Travis CI? When `dub test --config=console`, it seems to fail https://travis-ci.org/github/buggins/dlangui/builds/638566254

**Comment by NotSpooky** [comment]
This makes it compile for me

**Comment by Geod24** [comment]
Any chance we could get this (and the other PRs, #603 / #604 ) merged ? Ping @buggins

**Comment by Geod24** [comment]
Thanks!

**Pull request merged**
